### PR TITLE
[patch] change color when failed

### LINKED ISSUE #92: Nodes in a failed state should be glaringly obvious in the graph draw
Maybe outlined in bright red or something.

### PR DESCRIPTION
**Pull request by samwaseda**
Closes #92

```python
from pyiron_workflow import Workflow, function_node

def add(x, y):
    output = x + y
    return output

def mul(x, y=2):
    raise ValueError
    output = x * y
    return output

wf = Workflow("draw")
wf.Add = function_node(add, x=1, y=2)
wf.Mul = function_node(mul, x=wf.Add)

wf.run()
```

Screenshot 2024-09-20 at 08 25 22

Btw. does it have a particular reason that node has a color?

### CODE REVIEW

**Review by liamhuber — COMMENTED** [review]
I really liked how for the present/missing data you did just the outline -- could we port that to doing the outline in red here and leaving the fill the usual colour?

**Comment by liamhuber** [comment]
> Btw. does it have a particular reason that node has a color?

The end result should be that nodes of different types should have different colours (macros, function nodes, etc.) to improve visual clarity.

From a purity perspective, this should absolutely _not_ be a property of the node -- the `draw` method (or `pyiron-xyflow`) should handle it. But from a practical implementation perspective, that would mean that the drawer has its own colour map and is constantly doing `isinstance` checks to see which colour should be used -- grabbing `node.color` is much faster. I'm totally ok either route -- pure or practical, but practical is what there is right now.

**Comment by samwaseda** [comment]
> From a purity perspective, this should absolutely _not_ be a property of the node -- the `draw` method (or `pyiron-xyflow`) should handle it. But from a practical implementation perspective, that would mean that the drawer has its own colour map and is constantly doing `isinstance` checks to see which colour should be used -- grabbing `node.color` is much faster. I'm totally ok either route -- pure or practical, but practical is what there is right now.

ok it also sounds to me like we should have a possibility to export levels, and it sounds to me like it's something that `pyiron_workflow` should be able to do. I actually kinda have the feeling that the drawing module should also be better separated. I'll look into it at some point.

**Comment by samwaseda** [comment]
> I really liked how for the present/missing data you did just the outline -- could we port that to doing the outline in red here and leaving the fill the usual colour?

I updated it and also added an example in the top comment.

**Review by liamhuber — APPROVED** [review]

**Comment by liamhuber** [comment]
> we should have a possibility to export levels

Can you clarify this? IMO it's not as clear as "levels" of node -- that makes sense for function vs macro, but not so much for function vs transformer, or for loop vs macro.

**Comment by liamhuber** [comment]
> I actually kinda have the feeling that the drawing module should also be better separated. 

I see what you're saying, but I will disagree; I think it's nice to have some sort of built-in way of visualizing the nodes that comes with the library. It's a common enough operation that I'm disinclined to force people to separately install a second tool to get it done.

**Pull request merged**
