### PR TITLE
Draft: generic storage solution

### PR DESCRIPTION
**Pull request by XzzX**

### CODE REVIEW

**Comment by XzzX** [comment]
@liamhuber Seems like CI for branches in 3rd party repos do not work due to some tokens.

**Comment by XzzX** [comment]
@pyiron/storage Implementation of a `GenericStorage` heavily influenced by `tinybase`.

**Comment by liamhuber** [comment]
I don't think this repo is the right place for this PR; At the workshop we discussed keeping tools more isolated, and at least at this stage I don't see anything here that requires direct integration with the workflow code. Maybe move it to contrib or its own project?

**Comment by ligerzero-ai** [comment]
probably create a `pyiron_storage` or something along those lines and work on it there? Can clone/fork this repo if you need the CI.

**Comment by liamhuber** [comment]
> Ok. But "database" and long-term storage of workflows will most probably require it.

Maybe I've misunderstood your intent. Is this intended exclusively for saving/loading workflows, or might other pyiron projects be able to leverage it? If the former then this is the right spot, but I'd prefer to have the branch actually functionally save and load workflows before merging. 

> Just tell me where to put it and I will put it there.

If the latter, then my previous comment stands, and @ligerzero-ai's suggestion is a fine realization of it.

> ...Can clone/fork this repo if you need the CI.

Amendment: if you only care about the CI _infrastructure_ and not the associated workflow tests, making a new repo via [the template](https://github.com/pyiron/pyiron_module_template) will get you what you want with the least baggage.


[Per my previous comment](https://github.com/pyiron/specs/pull/66#issuecomment-2501590516), I've started working on this from the opposite side of parsing arbitrary (pickleable) objects.

**Comment by XzzX** [comment]
> probably create a `pyiron_storage` or something along those lines and work on it there? Can clone/fork this repo if you need the CI.

I do not need the complex CI setup you have in place. I can go with something much simpler. I will check the template repository.

**Comment by XzzX** [comment]
> > Ok. But "database" and long-term storage of workflows will most probably require it.
> 
> Maybe I've misunderstood your intent. Is this intended exclusively for saving/loading workflows, or might other pyiron projects be able to leverage it? If the former then this is the right spot, but I'd prefer to have the branch actually functionally save and load workflows before merging.

It's an implementation of our storage SPEC. Therefore, no, it is a general backend to store to different file formats. I thought this is the intention of the Storage SPEC. Please correct me if I am wrong.

I thought your workflow is to have everything in small reviewable pieces. This is why I started small and labeled it `draft`. If you want, I can make it feature complete first. But it will be larger than and changes are more complicated.

> 
> > Just tell me where to put it and I will put it there.
> 
> If the latter, then my previous comment stands, and @ligerzero-ai's suggestion is a fine realization of it.
> 

Ok.

> > ...Can clone/fork this repo if you need the CI.
> 
> Amendment: if you only care about the CI _infrastructure_ and not the associated workflow tests, making a new repo via [the template](https://github.com/pyiron/pyiron_module_template) will get you what you want with the least baggage.
> 
> [Per my previous comment](https://github.com/pyiron/specs/pull/66#issuecomment-2501590516), I've started working on this from the opposite side of parsing arbitrary (pickleable) objects.

I currently do not support arbitrary data types. I will add support for `dict` and `dataclasses`. I imagine integrating your stuff here. If you also want to implement the interface yourself, I am happy to use it. Then please point me to your version. I will need it for my work on the database.

**Comment by liamhuber** [comment]
> > > Ok. But "database" and long-term storage of workflows will most probably require it.
> > 
> > 
> > Maybe I've misunderstood your intent. Is this intended exclusively for saving/loading workflows, or might other pyiron projects be able to leverage it? If the former then this is the right spot, but I'd prefer to have the branch actually functionally save and load workflows before merging.
> 
> It's an implementation of our storage SPEC. Therefore, no, it is a general backend to store to different file formats. I thought this is the intention of the Storage SPEC. Please correct me if I am wrong.

I'm sorry, I'm not trying to be obtuse, I'm just legitimately very confused. It wasn't a "yes/no" question, and I unfortunately find the spec doc to still not clearly distinguish front-end workflow- and database-spefic stuff from the generic problem of storing (nearly) arbitrary data. Here you say this is meant to be generic, but further down you say

> I currently do not support arbitrary data types. I will add support for `dict` and `dataclasses`.

Which does not yet come close to encompassing even everything that can be pickled. So I'm just very confused.

> I thought your workflow is to have everything in small reviewable pieces. This is why I started small and labeled it `draft`. If you want, I can make it feature complete first. But it will be larger than and changes are more complicated.

The problem isn't the scope of the PR, which is lovely, it's just that as stated above it's still unclear to me if this is something workflow-specific, or a completely generic tool. If it is workflow-specific but that is just not clear at this early stage, I would suggest using stacked PRs until the feature is somehow usable by the workflows, but I am also open to it being merged earlier. If it's truly generic and won't depend on the workflow code at all, then this is simply the wrong place for the PR.

> If you also want to implement the interface yourself, I am happy to use it. Then please point me to your version. I will need it for my work on the database.
>
> I did not know you already started. Since this belongs to the storage SPEC, I thought you would tag me if you created your repo.

I started only on Tuesday and don't have a remote repo to point you to at present. I'll ping you via the storage group when possible.

**Comment by XzzX** [comment]
> > > > Ok. But "database" and long-term storage of workflows will most probably require it.
> > > 
> > > 
> > > Maybe I've misunderstood your intent. Is this intended exclusively for saving/loading workflows, or might other pyiron projects be able to leverage it? If the former then this is the right spot, but I'd prefer to have the branch actually functionally save and load workflows before merging.
> > 
> > 
> > It's an implementation of our storage SPEC. Therefore, no, it is a general backend to store to different file formats. I thought this is the intention of the Storage SPEC. Please correct me if I am wrong.
> 
> I'm sorry, I'm not trying to be obtuse, I'm just legitimately very confused. It wasn't a "yes/no" question, and I unfortunately find the spec doc to still not clearly distinguish front-end workflow- and database-spefic stuff from the generic problem of storing (nearly) arbitrary data. Here you say this is meant to be generic, but further down you say

You are not alone with your confusion. My current picture is `storage` has nothing to do with databases. I tried to remove all database related stuff from the spec. Indeed `storage` is a generic storage backend for arbitrary data. However, I put long-term storage over arbitrary data. I think including more and more datatypes increases maintanance, therefore, I would stick to some selected data types. As mentioned above, the current implementation only supports int, str, float and hierarchical storage. It is more about the general interface. For specific datatypes I am waiting for your implementation.

> 
> > I currently do not support arbitrary data types. I will add support for `dict` and `dataclasses`.
> 
> Which does not yet come close to encompassing even everything that can be pickled. So I'm just very confused.

I do not think we can achieve this without creating a huge maintanance burden. If you find a solution I am happy to change my mind.

> 
> > I thought your workflow is to have everything in small reviewable pieces. This is why I started small and labeled it `draft`. If you want, I can make it feature complete first. But it will be larger than and changes are more complicated.
> 
> The problem isn't the scope of the PR, which is lovely, it's just that as stated above it's still unclear to me if this is something workflow-specific, or a completely generic tool. If it is workflow-specific but that is just not clear at this early stage, I would suggest using stacked PRs until the feature is somehow usable by the workflows, but I am also open to it being merged earlier. If it's truly generic and won't depend on the workflow code at all, then this is simply the wrong place for the PR.

Ok, I moved everything to my own repository and create PRs against the SPECs to let you know about my progress and for discussion about the overall direction.  
https://github.com/pyiron/pyiron_xzzx/  
https://github.com/pyiron/specs/pull/75  
https://github.com/pyiron/specs/pull/76  

> 
> > If you also want to implement the interface yourself, I am happy to use it. Then please point me to your version. I will need it for my work on the database.
> > I did not know you already started. Since this belongs to the storage SPEC, I thought you would tag me if you created your repo.
> 
> I started only on Tuesday and don't have a remote repo to point you to at present. I'll ping you via the storage group when possible.

Looking forward to it.

**Pull request closed without merging**
