### PR TITLE
[patch] NodeJobOutput: Overload the save function to not change the job name

### PR DESCRIPTION
**Pull request by jan-janssen**
@srmnitc This should solve the issue with the cryptic job names to be more consistent with `pyiron_base`.

### CODE REVIEW

**Comment by jan-janssen** [comment]
The updated notebook is available in https://gitlab.mpcdf.mpg.de/janj/dpg_tutorial_2024/-/blob/main/workflows/stress_strain.ipynb - here the job names are no longer cryptic but rather the job names are the ones given in the `pr.create.job.NodeJob()` function call.

**Review by liamhuber — COMMENTED** [review]
@srmnitc, @jan-janssen, I still prefer #226, but I made my desired changes here. In case base can't be updated in time, this can be merged and new patch release (0.4.2) can be made.

**Review by liamhuber — APPROVED** [review]

**Review by liamhuber — COMMENTED** [review]
Sorry for the noise, I'm just trying to get the request for changes removed but also have the review status as "Comment"

**Comment by liamhuber** [comment]
> Sorry for the noise, I'm just trying to get the request for changes removed but also have the review status as "Comment"

I give up.

**Comment by liamhuber** [comment]
Per [the meeting discussion](https://github.com/orgs/pyiron/discussions/217#discussioncomment-8593706) we'll merge this now so we can get the functionality without any updates to base. I'll draft a reverting PR so we can proceed with the #227 solution once base is moving.

**Pull request merged**
