### PR TITLE
Update several dependencies at once

### PR DESCRIPTION
**Pull request by niklassiemer**

### CODE REVIEW

**Comment by niklassiemer** [comment]
@liamhuber I prepared a release, if this fits for you, I would release it on the weekend to get the versions of pyiron_atomistics up to date on the cluster :)

**Comment by liamhuber** [comment]
@niklassiemer thanks for handling the codependent updates!

Will it be a problem to hold until Monday? I have a big fix  PR ready to go, but am experiencing a pycharm-GitHub issue; I should be able to make a release by Sunday evening though

**Comment by niklassiemer** [comment]
No, would be a-ok as well. I just wanted the dependbot PRs to fetch the update on Monday, such that I could have a new consistent environment including pyiron_snippets etc. by the next deploy to cmti on tuesday. However, otherwise it simply stays similar for another week ;)

**Comment by liamhuber** [comment]
Super, I'll get it out as soon as I can!

**Pull request merged**
