### PR TITLE
File object str

### PR DESCRIPTION
**Pull request by samwaseda**
```python
file_object = FileObject("my_file", "/path/to/my/file")
print(str(file_object))
```

Output: `/path/to/my/file/my_file`

### CODE REVIEW

**Comment by samwaseda** [comment]
I made a mistake with the PR: I wanted to merge to [this PR](https://github.com/pyiron/pyiron_workflow/pull/214) but I chose main instead. So I change it to draft as long as the other one is not merged.

**Comment by liamhuber** [comment]
> I made a mistake with the PR: I wanted to merge to [this PR](https://github.com/pyiron/pyiron_workflow/pull/214) but I chose main instead. So I change it to draft as long as the other one is not merged.

It's a holiday here so I won't have time to review until tomorrow morning, but you can change the reference by editing the pr after creation

**Comment by samwaseda** [comment]
I'm not sure if `__str__` should give the file name or the absolute path. Let me know what you think

**Comment by liamhuber** [comment]
@samwaseda, I enjoy reading your commit messages :joy:

**Pull request merged**
